# Use the official PostgreSQL image from Docker Hub
FROM postgres:16

# Set environment variables (change these as needed)
ENV POSTGRES_DB=savethechicken
ENV POSTGRES_USER=savethechicken
ENV POSTGRES_PASSWORD=savethechicken

# Expose the PostgreSQL port
EXPOSE 5432
